[build]
  command = "npm run build"     # your build command
  publish = "dist"              # folder to publish
  functions = "netlify/functions" # location of your serverless functions

[functions]
  node_bundler = "esbuild"      # faster bundling (recommended)

[build.environment]
  NODE_VERSION = "20"

